name: point-imagery
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12.9
  - pip=25.0.1
  - snakemake=8.29.2
  - pandas=2.2.3
  - numpy=2.2.3
  - matplotlib=3.9.4
  - gdal=3.10.2
  - geopandas=1.0.1
  - astropy=7.0.1
  - utm=0.7.0
  - planetary-computer=1.0.0
  - pip:
    - pystac-client==0.8.6